apiVersion: apps/v1
kind: Deployment
metadata:
  name: tor-proxy
  labels:
    app: tor-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tor-proxy
  template:
    metadata:
      labels:
        app: tor-proxy
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: tor-proxy
        image: jess/tor-proxy:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1000Mi"
            cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: tor-proxy
spec:
  selector:
    app: tor-proxy
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
