---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: airprint
  name: airprint
  namespace: airprint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airprint
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: airprint
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - image: firilith/airprint
        env:
        - name: CUPSADMIN
          value: "admin"
        - name: CUPSPASSWORD
          value: "admin"
        - name: TZ
          value: "America/New_York"
        name: airprint
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: airprint
  name: airprint
  namespace: airprint
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 631
    targetPort: 631
  selector:
    run: airprint
  type: LoadBalancer
