---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: LAN homebridge
    name: homebridge
  labels:
    app: homebridge
  name: homebridge
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: homebridge
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        description: LAN homebridge
      labels:
        app: homebridge
      name: homebridge
    spec:
      containers:
        - env:
            - name: TZ
              value: America/New_York
            - name: ENABLE_AVAHI
              value: '0'
          image: oznu/homebridge:2023-01-08
          name: homebridge
          ports:
            - containerPort: 8581
              name: homebridge-ui
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
          securityContext:
            privileged: true
            procMount: Default
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
