apiVersion: v1
kind: Service
metadata:
  labels:
    app: homebridge
  name: homebridge
spec:
  ports:
    - name: homebridge
      port: 51827
      targetPort: homebridge
    - name: homebridge-2
      port: 5353
      targetPort: homebridge-2
  selector:
    app: homebridge
  type: LoadBalancer
