apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: lan-loadbalancer
    metallb.universe.tf/allow-shared-ip: lan-loadbalancer
  labels:
    k8s-app: homebridge
  name: homebridge-100
spec:
  ports:
  - name: homebridge
    port: 51827
    targetPort: homebridge
  - name: homebridge-2
    port: 5353
    targetPort: homebridge-2
  selector:
    k8s-app: homebridge
  type: LoadBalancer
