apiVersion: v1
kind: Service
metadata:
  labels:
    app: homebridge
  name: homebridge
spec:
  ports:
    - name: homebridge-ui
      port: 80
      targetPort: homebridge-ui
  selector:
    app: homebridge
  type: LoadBalancer
